[ADD] a maximum amount of retries to the docker connection checking

diff --git a/.github/workflows/run_unit_tests.yaml b/.github/workflows/run_unit_tests.yaml
--- a/.github/workflows/run_unit_tests.yaml
+++ b/.github/workflows/run_unit_tests.yaml
@@ -86,20 +86,27 @@ jobs:
       - name: Start the docker compose
         run: |
           docker compose up -d
-
       - name: Check for database connection
         run: |
           CONTAINER_NAME="db_connection_tester"
           RUN_COMMAND="apt install -y mariadb-client && echo 'exit' | mariadb -u root -proot -h ${{env.DATABASE_CONTAINER_NAME}}"
+          MAX_RETRIES=10  # Set your maximum retry count here
+          RETRY_COUNT=0
           until docker run --rm \
             --name $CONTAINER_NAME \
             --network ${{env.DOCKER_NETWORK}} \
             -t ${{env.SERVER_IMAGE_NAME}} \
             /bin/bash -c "$RUN_COMMAND"; do
-              echo "Waiting for the database to be ready..."
+              RETRY_COUNT=$((RETRY_COUNT+1))
+              if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
+                echo "Max retries reached, could not connect to the database."
+                exit 1
+              fi
+              echo "Waiting for the database to be ready... ($RETRY_COUNT/$MAX_RETRIES)"
               sleep 5
           done
           echo "Database connection established."
+
 
       - name: Show running containers
         run: |
